### ISSUE TITLE
Unable to configure email notifications

### ISSUE THREAD

**Issue by jose-matos** [fedora-infra/fmn.web#75]
I want to configure the notifications to receive email for the messages I am 
interested in.

I go to https://apps.fedoraproject.org/notifications/

and login.

Then I choose email and I add the email address I am interest in receiving the 
notification messages.

In less than a minute I receive an email from notifications@fedoraproject.org 
with a link to confirm the email address.

The problem occurs in the next step if I choose to accept I always get an 
unauthorized access error from fas login:

401 - Unauthorized

Transaction expired, or cookies not available

Try to login again

This has happened to me always, ever since this service was announced, and now I would like to finally solve this issue.

**Comment by pypingou** [comment]
Could you share which url exactly is returning you a 401?
Do you use any specific plugin in your browser?

**Comment by jose-matos** [comment]
An example I got a message to accept:
https://apps.fedoraproject.org/notifications/confirm/accept/0eb81a61ef3ce6c35d9ce5710d6275ce

and the page where I get the unauthorized access is
https://id.fedoraproject.org/login/fas?ipsilon_transaction_id=1df82bc1-8fc2-4437-9d67-ed682742aaf2

FWIW I am using Firefox with the EFF privacy badger

**Comment by jose-matos** [comment]
I have changed browser to accept the notification, I used QupZilla that is installed, and this time has worked...

Strange...

**Comment by pypingou** [comment]
So it's likely related to that EFF privacy plugin you're using.

I know ipsilon's upstream was looking to replicate the problem but looks like you figured out a way around quicker :)
